import {
  AlertTriangle,
  ArrowRight,
  BarChart,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  type Icon as LucideIcon,
  Image,
  Laptop,
  Library,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  TestTube2,
  TestTubes,
  Trash,
  Twitter,
  User,
  Users,
  X,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  logo: TestTube2,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  check: Check,
  experiments: TestTubes,
  users: Users,
  library: Library,
  stats: BarChart,
};
